/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.cassandra.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Identifies what type of storage to use
 */
public enum StorageType implements org.apache.thrift.TEnum {
  CFS_REGULAR(0),
  CFS_ARCHIVE(1);

  private final int value;

  private StorageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static StorageType findByValue(int value) { 
    switch (value) {
      case 0:
        return CFS_REGULAR;
      case 1:
        return CFS_ARCHIVE;
      default:
        return null;
    }
  }
}
