//
// Autogenerated by Thrift
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
Position = function(args){
this.ticker = null
this.price = null
this.shares = null
if( args != null ){if (null != args.ticker)
this.ticker = args.ticker
if (null != args.price)
this.price = args.price
if (null != args.shares)
this.shares = args.shares
}}
Position.prototype = {}
Position.prototype.read = function(input){ 
var ret = input.readStructBegin()
while (1) 
{
  var ret = input.readFieldBegin()
  var fname = ret.fname
  var ftype = ret.ftype
  var fid   = ret.fid
  if (ftype == Thrift.Type.STOP) 
    break
  switch(fid)
  {
    case 1:    if (ftype == Thrift.Type.STRING) {
      var rtmp = input.readString()
this.ticker = rtmp.value
    } else {
      input.skip(ftype)
    }
    break
    case 2:    if (ftype == Thrift.Type.DOUBLE) {
      var rtmp = input.readDouble()
this.price = rtmp.value
    } else {
      input.skip(ftype)
    }
    break
    case 3:    if (ftype == Thrift.Type.I64) {
      var rtmp = input.readI64()
this.shares = rtmp.value
    } else {
      input.skip(ftype)
    }
    break
    default:
      input.skip(ftype)
  }
  input.readFieldEnd()
}
input.readStructEnd()
return
}

Position.prototype.write = function(output){ 
output.writeStructBegin('Position')
if (null != this.ticker) {
  output.writeFieldBegin('ticker', Thrift.Type.STRING, 1)
  output.writeString(this.ticker)
  output.writeFieldEnd()
}
if (null != this.price) {
  output.writeFieldBegin('price', Thrift.Type.DOUBLE, 2)
  output.writeDouble(this.price)
  output.writeFieldEnd()
}
if (null != this.shares) {
  output.writeFieldBegin('shares', Thrift.Type.I64, 3)
  output.writeI64(this.shares)
  output.writeFieldEnd()
}
output.writeFieldStop()
output.writeStructEnd()
return
}

Portfolio = function(args){
this.name = null
this.constituents = null
this.basis = null
this.price = null
this.largest_10day_loss = null
this.largest_10day_loss_date = null
this.hist_prices = null
if( args != null ){if (null != args.name)
this.name = args.name
if (null != args.constituents)
this.constituents = args.constituents
if (null != args.basis)
this.basis = args.basis
if (null != args.price)
this.price = args.price
if (null != args.largest_10day_loss)
this.largest_10day_loss = args.largest_10day_loss
if (null != args.largest_10day_loss_date)
this.largest_10day_loss_date = args.largest_10day_loss_date
if (null != args.hist_prices)
this.hist_prices = args.hist_prices
}}
Portfolio.prototype = {}
Portfolio.prototype.read = function(input){ 
var ret = input.readStructBegin()
while (1) 
{
var ret = input.readFieldBegin()
var fname = ret.fname
var ftype = ret.ftype
var fid   = ret.fid
if (ftype == Thrift.Type.STOP) 
  break
switch(fid)
{
  case 1:  if (ftype == Thrift.Type.STRING) {
    var rtmp = input.readString()
this.name = rtmp.value
  } else {
    input.skip(ftype)
  }
  break
  case 2:  if (ftype == Thrift.Type.LIST) {
    {
      var _size0 = 0
      var rtmp3
      this.constituents = []
      var _etype3 = 0
      rtmp3 = input.readListBegin()
      _etype3 = rtmp3.etype
      _size0 = rtmp3.size
      for (var _i4 = 0; _i4 < _size0; ++_i4)
      {
        var elem5 = null
        elem5 = new Position()
        elem5.read(input)
        this.constituents.push(elem5)
      }
      input.readListEnd()
    }
  } else {
    input.skip(ftype)
  }
  break
  case 3:  if (ftype == Thrift.Type.DOUBLE) {
    var rtmp = input.readDouble()
this.basis = rtmp.value
  } else {
    input.skip(ftype)
  }
  break
  case 4:  if (ftype == Thrift.Type.DOUBLE) {
    var rtmp = input.readDouble()
this.price = rtmp.value
  } else {
    input.skip(ftype)
  }
  break
  case 5:  if (ftype == Thrift.Type.DOUBLE) {
    var rtmp = input.readDouble()
this.largest_10day_loss = rtmp.value
  } else {
    input.skip(ftype)
  }
  break
  case 6:  if (ftype == Thrift.Type.STRING) {
    var rtmp = input.readString()
this.largest_10day_loss_date = rtmp.value
  } else {
    input.skip(ftype)
  }
  break
  case 7:  if (ftype == Thrift.Type.LIST) {
    {
      var _size6 = 0
      var rtmp3
      this.hist_prices = []
      var _etype9 = 0
      rtmp3 = input.readListBegin()
      _etype9 = rtmp3.etype
      _size6 = rtmp3.size
      for (var _i10 = 0; _i10 < _size6; ++_i10)
      {
        var elem11 = null
        var rtmp = input.readDouble()
elem11 = rtmp.value
        this.hist_prices.push(elem11)
      }
      input.readListEnd()
    }
  } else {
    input.skip(ftype)
  }
  break
  default:
    input.skip(ftype)
}
input.readFieldEnd()
}
input.readStructEnd()
return
}

Portfolio.prototype.write = function(output){ 
output.writeStructBegin('Portfolio')
if (null != this.name) {
output.writeFieldBegin('name', Thrift.Type.STRING, 1)
output.writeString(this.name)
output.writeFieldEnd()
}
if (null != this.constituents) {
output.writeFieldBegin('constituents', Thrift.Type.LIST, 2)
{
  output.writeListBegin(Thrift.Type.STRUCT, this.constituents.length)
  {
    for(var iter12 in this.constituents)
    {
      iter12=this.constituents[iter12]
      iter12.write(output)
    }
  }
  output.writeListEnd()
}
output.writeFieldEnd()
}
if (null != this.basis) {
output.writeFieldBegin('basis', Thrift.Type.DOUBLE, 3)
output.writeDouble(this.basis)
output.writeFieldEnd()
}
if (null != this.price) {
output.writeFieldBegin('price', Thrift.Type.DOUBLE, 4)
output.writeDouble(this.price)
output.writeFieldEnd()
}
if (null != this.largest_10day_loss) {
output.writeFieldBegin('largest_10day_loss', Thrift.Type.DOUBLE, 5)
output.writeDouble(this.largest_10day_loss)
output.writeFieldEnd()
}
if (null != this.largest_10day_loss_date) {
output.writeFieldBegin('largest_10day_loss_date', Thrift.Type.STRING, 6)
output.writeString(this.largest_10day_loss_date)
output.writeFieldEnd()
}
if (null != this.hist_prices) {
output.writeFieldBegin('hist_prices', Thrift.Type.LIST, 7)
{
  output.writeListBegin(Thrift.Type.DOUBLE, this.hist_prices.length)
  {
    for(var iter13 in this.hist_prices)
    {
      iter13=this.hist_prices[iter13]
      output.writeDouble(iter13)
    }
  }
  output.writeListEnd()
}
output.writeFieldEnd()
}
output.writeFieldStop()
output.writeStructEnd()
return
}

