-- Statement: DROP TABLE IF EXISTS ctas_source_table
-- Statement: DROP TABLE IF EXISTS ctas_target_table
-- Statement: CREATE TABLE ctas_source_table (foo INT, bar STRING) COMMENT 'table to test CTAS'
-- Statement: LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv1.txt' OVERWRITE INTO TABLE ctas_source_table
-- Statement: SELECT COUNT(*) FROM ctas_source_table
500, 
-- Statement: CREATE TABLE ctas_target_table as SELECT * FROM ctas_source_table
-- Statement: SELECT COUNT(*) FROM ctas_target_table
500, 
-- Statement: DROP TABLE ctas_target_table
-- Statement: DROP TABLE ctas_source_table
