-- Statement: DROP TABLE IF EXISTS alter_test_table
-- Statement: DROP TABLE IF EXISTS alter_test_table_ctas
-- Statement: DROP TABLE IF EXISTS alter_test_table_renamed
-- Statement: CREATE TABLE alter_test_table (foo INT, bar STRING) COMMENT 'table to test DDL ops' PARTITIONED BY (ds STRING) STORED AS TEXTFILE
-- Statement: LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv1.txt' OVERWRITE INTO TABLE alter_test_table PARTITION (ds='2008-08-08')
-- Statement: CREATE TABLE alter_test_table_ctas as SELECT * FROM alter_test_table
-- Statement: DESCRIBE alter_test_table_ctas
foo, int, , 
bar, string, , 
ds, string, , 
-- Statement: ALTER TABLE alter_test_table ADD COLUMNS (new_col1 INT)
-- Statement: INSERT OVERWRITE TABLE alter_test_table PARTITION (ds='2008-08-15') SELECT foo, bar, 333333333 FROM alter_test_table_ctas WHERE ds='2008-08-08'
-- Statement: ALTER TABLE alter_test_table ADD COLUMNS (new_col2 STRING, new_col3 STRING COMMENT 'a comment')
-- Statement: INSERT OVERWRITE TABLE alter_test_table PARTITION (ds='2008-08-18') SELECT foo, bar, 12345678, 'new string to insert', '2011-05-07' FROM alter_test_table WHERE ds='2008-08-18'
-- Statement: ALTER TABLE alter_test_table CHANGE new_col1 new_col1a STRING after new_col2
-- Statement: ALTER TABLE alter_test_table CHANGE bar bar STRING FIRST
-- Statement: ALTER TABLE alter_test_table CHANGE foo foo INT FIRST
-- Statement: LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv3.txt' OVERWRITE INTO TABLE alter_test_table PARTITION (ds='2008-08-22')
-- Statement: SHOW PARTITIONS alter_test_table
cfs://null/user/hive/warehouse/alter_test_table/ds=2008-08-08, 
cfs://null/user/hive/warehouse/alter_test_table/ds=2008-08-15, 
cfs://null/user/hive/warehouse/alter_test_table/ds=2008-08-18, 
cfs://null/user/hive/warehouse/alter_test_table/ds=2008-08-22, 
-- Statement: DESCRIBE alter_test_table
foo, int, , 
bar, string, , 
new_col2, string, , 
new_col1a, string, , 
new_col3, string, a comment, 
ds, string, , 
-- Statement: SELECT count(*), ds FROM alter_test_table GROUP BY ds
500, 2008-08-08, 
500, 2008-08-15, 
25, 2008-08-22, 
-- Statement: ALTER TABLE alter_test_table RENAME TO alter_test_table_renamed
-- Statement: LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv3.txt' OVERWRITE INTO TABLE alter_test_table_renamed PARTITION (ds='2008-08-22')
-- Statement: ALTER TABLE alter_test_table_renamed ADD COLUMNS (new_col_after_rename INT COMMENT 'a comment')
-- Statement: ALTER TABLE alter_test_table_renamed replace columns (foo2 INT, bar2 STRING)
-- Statement: ALTER TABLE alter_test_table_renamed change foo2 foo3 INT
-- Statement: ALTER TABLE alter_test_table_renamed change bar2 bar3 STRING FIRST
-- Statement: LOAD DATA LOCAL INPATH '[[EXAMPLES]]/kv3.txt' OVERWRITE INTO TABLE alter_test_table_renamed PARTITION (ds='2008-08-08')
-- Statement: ALTER TABLE alter_test_table_renamed TOUCH
-- Statement: ALTER TABLE alter_test_table_renamed TOUCH PARTITION (ds='2008-08-08')
-- Statement: ALTER TABLE alter_test_table_renamed TOUCH PARTITION (ds='2008-08-15')
-- Statement: SHOW PARTITIONS alter_test_table_renamed
cfs://null/user/hive/warehouse/alter_test_table_renamed/ds=2008-08-08, 
cfs://null/user/hive/warehouse/alter_test_table_renamed/ds=2008-08-15, 
cfs://null/user/hive/warehouse/alter_test_table_renamed/ds=2008-08-18, 
cfs://null/user/hive/warehouse/alter_test_table_renamed/ds=2008-08-22, 
-- Statement: DESCRIBE alter_test_table_renamed
bar3, string, , 
foo3, int, , 
ds, string, , 
-- Statement: SELECT ds, COUNT(*) FROM alter_test_table_renamed GROUP BY ds
2008-08-08, 25, 
2008-08-15, 500, 
2008-08-22, 25, 
-- Statement: DROP TABLE alter_test_table_renamed
-- Statement: DROP TABLE alter_test_table_ctas
