-- Statement: DROP TABLE IF EXISTS mixedCaSE
-- Statement: DROP TABLE IF EXISTS mixedCaSE_renamed
-- Statement: DROP TABLE IF EXISTS mixedCaSE_clike
-- Statement: DROP TABLE IF EXISTS mixedCaSE_ctas
-- Statement: CREATE TABLE mixedCaSE (foo INT, bar STRING) COMMENT 'table to test DDL ops' PARTITIONED BY (ds STRING) STORED AS TEXTFILE
-- Statement: CREATE TABLE mixedCaSE_clike LIKE mixedCaSE
-- Statement: DESCRIBE mixedCaSE_clike
foo, int, , 
bar, string, , 
ds, string, , 
-- Statement: CREATE TABLE mixedCaSE_ctas as SELECT * FROM mixedCaSE
-- Statement: DESCRIBE mixedCaSE
foo, int, , 
bar, string, , 
ds, string, , 
-- Statement: ALTER TABLE mixedCaSE ADD COLUMNS (new_col1 INT)
-- Statement: INSERT OVERWRITE TABLE mixedCaSE PARTITION (ds='2008-08-15') SELECT foo, bar, 333333333 FROM mixedCaSE_ctas WHERE ds='2008-08-08'
-- Statement: ALTER TABLE mixedCaSE ADD COLUMNS (new_col2 STRING, new_col3 STRING COMMENT 'a comment')
-- Statement: INSERT OVERWRITE TABLE mixedCaSE PARTITION (ds='2008-08-18') SELECT foo, bar, 12345678, 'new string to insert', '2011-05-07' FROM mixedCaSE WHERE ds='2008-08-18'
-- Statement: ALTER TABLE mixedCaSE CHANGE new_col1 new_col1a STRING after new_col2
-- Statement: ALTER TABLE mixedCaSE CHANGE bar bar STRING FIRST
-- Statement: ALTER TABLE mixedCaSE CHANGE foo foo INT FIRST
-- Statement: SHOW PARTITIONS mixedCaSE
-- Statement: DESCRIBE mixedCaSE
foo, int, , 
bar, string, , 
new_col2, string, , 
new_col1a, string, , 
new_col3, string, a comment, 
ds, string, , 
-- Statement: SELECT count(*), ds FROM mixedCaSE GROUP BY ds
-- Statement: ALTER TABLE mixedCaSE RENAME TO mixedCaSE_renamed
-- Statement: DESCRIBE mixedCaSE_renamed
foo, int, , 
bar, string, , 
new_col2, string, , 
new_col1a, string, , 
new_col3, string, a comment, 
ds, string, , 
-- Statement: SHOW PARTITIONS mixedCaSE_renamed
-- Statement: DESCRIBE mixedCaSE_renamed
foo, int, , 
bar, string, , 
new_col2, string, , 
new_col1a, string, , 
new_col3, string, a comment, 
ds, string, , 
-- Statement: SELECT ds, COUNT(*) FROM mixedCaSE_renamed GROUP BY ds
-- Statement: DROP TABLE mixedCaSE_renamed
-- Statement: DROP TABLE mixedCaSE_clike
-- Statement: DROP TABLE mixedCaSE_ctas
