-- Statement: SELECT COUNT(*), COUNT(distinct userid) FROM u_data
100000, 943, 
-- Statement: ADD FILE [[DATA_DIR]]/weekday_mapper.py
-- Statement: INSERT OVERWRITE TABLE u_data_new SELECT TRANSFORM (userid, movieid, rating, unixtime) USING 'python weekday_mapper.py' AS (userid, movieid, rating, weekday) FROM u_data
-- Statement: SELECT weekday, COUNT(*) FROM u_data_new GROUP BY weekday
1, 13341, 
2, 14337, 
3, 15812, 
4, 13469, 
5, 18489, 
6, 12508, 
7, 12044, 
