demos/portfolio_manager/portfolio.jar usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/bin usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/resources usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/thrift usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/website usr/share/brisk-demos/portfolio_manager
demos/portfolio_manager/README.txt usr/share/brisk-demos/portfolio_manager
