#!/bin/bash
#
# /etc/init.d/cassandra
#
# Startup script for Cassandra
# 
# chkconfig: 2345 20 80
# description: Starts and stops Cassandra

. /etc/rc.d/init.d/functions

export JAVA_HOME=/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0/
export CASSANDRA_HOME=/usr/share/brisk/cassandra/
export CASSANDRA_INCLUDE=/usr/share/cassandra/cassandra.in.sh
export CASSANDRA_CONF=/etc/brisk/cassandra
export CASSANDRA_OWNR=cassandra
NAME="cassandra"
log_file=/var/log/cassandra/cassandra.log
pid_file=/var/run/cassandra/cassandra.pid
HADOOP_ENABLED=0
# enable overcommit if you enable hadoop
OVERCOMMIT_ENABLED=0
EXTRA_FLAGS=""
# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
# brisk specific settings
[ -r /etc/default/brisk ] && . /etc/default/brisk

CASSANDRA_PROG=/usr/sbin/cassandra

case "$1" in
    start)
        # Cassandra startup
        if [ "$OVERCOMMIT_ENABLED" = "1" ]; then
        	/sbin/sysctl -w vm.overcommit_memory = 1
        fi
        if [ "$HADOOP_ENABLED" = "0" ]; then
    		echo "Brisk daemon starting with Hadoop disabled (edit /etc/default/brisk to enable)"
		else
			# load brisk env
			[ -e /etc/brisk/brisk-env.sh ] || exit 0
			# Read Brisk environment file.
			. /etc/brisk/brisk-env.sh			
			EXTRA_FLAGS="$EXTRA_FLAGS -t -Djava.library.path=$JAVA_LIBRARY_PATH"			   		
    		echo "Brisk daemon starting with Hadoop enabled (edit /etc/default/brisk to disable)"
		fi
        
        echo -n "Starting Cassandra: "        
        su $CASSANDRA_OWNR -c "$CASSANDRA_PROG -p $pid_file $EXTRA_FLAGS" > $log_file 2>&1
        echo "OK"
        ;;
    stop)
        # Cassandra shutdown
        echo -n "Shutdown Cassandra: "
        su $CASSANDRA_OWNR -c "kill `cat $pid_file`"
        echo "OK"
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    status)
        status -p $pid_file cassandra
        ;;
    *)
        echo "Usage: `basename $0` start|stop|status|restart|reload"
        exit 1
esac

exit 0

